korman/properties/modifiers/render.py, korman/ui/modifiers/render.py
The `ViewFaceMod` is presented as a Swivel component, with artist-ready presets for the typical Sprite and Billboard, as well as an advanced 'Custom' option which exposes additional features.
=> Add ViewFaceMods.

korman/exporter/mesh.py, korman/exporter/rtlight.py, korman/nodes/__init__.py, korman/nodes/node_core.py, korman/nodes/node_softvolume.py, korman/properties/modifiers/region.py, korman/properties/modifiers/render.py, korman/ui/modifiers/region.py, korman/ui/modifiers/render.py
=> Soft Volumes and Vis Regions

korman/exporter/rtlight.py
This gives a much better error when it works correctly. :smirk:
=> Fix typo in exception name so error reporting doesn't throw an error.

korman/exporter/material.py
For lamp flare blending :trollface:
=> Port better alpha blending from PyPRP

korman/exporter/convert.py, korman/exporter/etlight.py, korman/exporter/mesh.py, korman/helpers.py, korman/operators/op_export.py, korman/operators/op_lightmap.py, korman/properties/modifiers/render.py, korman/ui/modifiers/render.py
Refactors the lightmap modifier to limit calls to bake_image as requested on the forum https://forum.guildofwriters.org/viewtopic.php?f=114&t=6663. Also allows for the selection of render layers on the lightmap modifier.
Ping @Deledrius @Jirus
=> Lightmap Modifier Refactor

korman/exporter/material.py, korman/exporter/mesh.py, korman/exporter/rtlight.py, korman/properties/modifiers/water.py
=> Projection Lights

korman/exporter/animation.py, korman/exporter/convert.py, korman/exporter/material.py, korman/exporter/rtlight.py, korman/nodes/node_messages.py, korman/properties/modifiers/anim.py, korman/properties/modifiers/physics.py, korman/properties/modifiers/sound.py, korman/ui/modifiers/anim.py
This implements several new animation types:
- Sound Volume
- Lamp Color
- Spot Cone
- Omni Lamp
Also, the animation modifier has been demoted from "requirement" to just a plATCAnim helper.
=> Moar Animations

korlib/texture.cpp, korman/exporter/material.py, korman/korlib/__init__.py, korman/korlib/texture.py, korman/properties/prop_texture.py, korman/ui/ui_texture.py
@Deledrius I'd appreciate a cursory review and some suggestions for the UI descriptions.
=> Implement detail fading for Plasma Layers

korman/exporter/material.py
Blender's Texture "Extend" option is what actually matches Plasma's definition of "clamping".
=> Layers should also be clamped with EXTEND

korman/exporter/explosions.py, korman/exporter/physics.py, korman/nodes/node_python.py, korman/properties/modifiers/water.py, korman/ui/modifiers/water.py
=> Swim Regions

korman/operators/op_toolbox.py, korman/ui/ui_toolbox.py
In the spirit of [dendwaler's request](https://forum.guildofwriters.org/viewtopic.php?p=71399#p71399), some more Plasma Object tools have been added. The Plasma Object converter will actually inspect old page_num properties used by PyPRP and put those objects into the correct pages. The artist will have to set them up in the age settings first however.
=> Moar Toolbox Schtuff

korman/exporter/physics.py
In preparation for public 64-bit builds... This moves convex hull generation from the file serialization stage to the object export stage. No longer are we dependent on spotty library support for proper convex hulls. I expect this change will result in slightly smaller file sizes as well.
=> Convex Hull Improvement

korman/korlib/__init__.py, korman/properties/modifiers/sound.py
Some fixes to prevent crashes when using Wave files in Sound Emitters.
=> Wave file fixes.

korman/nodes/node_python.py, korman/properties/modifiers/__init__.py, korman/properties/modifiers/gui.py, korman/ui/modifiers/__init__.py, korman/ui/modifiers/gui.py
Adds a simplified Journal Modifier which automatically creates the PFM and associated nodes, as well as a temporary default region for the conditional if one is not provided by the artist.
Closes #34.
=> Add a simple JournalMod.

korman/exporter/etlight.py, korman/operators/op_lightmap.py
https://forum.guildofwriters.org/viewtopic.php?p=71500#p71500
=> Fix Lightmapping Issues

korman/exporter/material.py
This also allows you to turn off preshade/runtime colouring.
=> Add support for specular layers

korman/exporter/material.py, korman/ui/ui_texture.py
* Export a root node for DynamicEnvMaps, where supported (libHSPlasma handles this, but I think it's only MystV & MOUL)
* Fix a weird vanishing UI field with the DEM visRegion panel
=> DynaEnvMap fixes

korman/operators/op_export.py, korman/operators/op_world.py, korman/properties/__init__.py, korman/properties/modifiers/logic.py, korman/properties/prop_world.py, korman/ui/ui_world.py
This begins addressing an ancillary item from #41. Merge as-is or wait for more functionality? Seems to me that the one button press simple export targeting to multiple games is good enough for now.
=> Game tracker

korman/nodes/__init__.py, korman/nodes/node_conditions.py, korman/nodes/node_core.py, korman/nodes/node_deprecated.py, korman/nodes/node_messages.py, korman/nodes/node_responder.py, korman/properties/modifiers/region.py
=> Deprecated Responder Command Nodes

korman/nodes/node_messages.py
Otherwise it appears to never actually trigger the waitOn for messages further down the chain
=> Add callbacks flag to chained AnimCmdMsgs

korman/nodes/node_responder.py
In order for a python script to be notified that a responder attribute has finished executing, we have to have a callback notify message in the responder state. Cyan seems to require the artist to do this by hand, but that seems like such a common operation that we'll add a callback at the end of every state of any responder linked to a Python node. Cyan's approach is somewhat more flexible in that you can call back at any point in the responder, but that seems a bit excessive.
=> Fix responder nodes not notifying python nodes

korman/nodes/node_deprecated.py, korman/nodes/node_responder.py, korman/properties/modifiers/__init__.py, korman/properties/modifiers/base.py, korman/properties/modifiers/render.py
Required for #118. Fixes #120.
=> Modifier Upgrading

korman/nodes/node_conditions.py, korman/nodes/node_core.py, korman/nodes/node_python.py, korman/nodes/node_responder.py, korman/operators/op_nodes.py
Adds the ability to create and link Korman nodes directly to the node sockets.
=> Node Improvements

korman/nodes/node_avatar.py, korman/nodes/node_python.py
Add MultiStage Behaviour, AnimationStage, and SeekTarget nodes.
Closes #45.
=> Add MultiStageBehMod Node.

korman/exporter/utils.py, korman/properties/modifiers/base.py, korman/properties/modifiers/gui.py, korman/ui/modifiers/gui.py
Adds a simplified LinkingBook Modifier which automatically creates the PFM and associated nodes, as well as a temporary default region for the conditional if one is not provided by the artist.
=> Add a simple LinkingBook Modifier.

korman/nodes/node_avatar.py, korman/nodes/node_messages.py
- Allow triggering responders and sitting behaviors from MSBs.
- Fix strange log message formatter to use the more detailed `raise_error` method.
- Allow triggering MSBs from Responders for @dpogue.
=> Fix oversights in MSBs.

korman/exporter/mesh.py
This seems to be the same flag Cyan [uses](https://github.com/H-uru/Plasma/blob/47f0899d1edc830ad54697f970b19639e0e8f098/Sources/Tools/MaxConvert/plMeshConverter.cpp#L1205-L1212) for marking geospans as needing to be in BlendSpans, conveniently enough for us
=> Ensure alpha vcol paint makes a BlendSpan

korman/exporter/mesh.py
Prevent export of Blender Decimate modifier from failing and corrupting Blender file!
=> Fix bugs caused by using Decimate modifier

korman/properties/modifiers/water.py
A long time coming but only now just fixed, this makes a small correction to the wind object part of the waveset modifier to get it to work.
=> Wind Object fix

korman/exporter/material.py, korman/nodes/node_python.py, korman/properties/modifiers/render.py, korman/ui/modifiers/render.py
Attached is a sample Age with a crude multiplayer capable, real-time grass wave editor.
[KormanGrass.zip](https://github.com/H-uru/korman/files/6388555/KormanGrass.zip)
=> Add grass shader modifier (MOUL only).

korman/exporter/convert.py, korman/exporter/physics.py, korman/nodes/node_messages.py, korman/properties/modifiers/physics.py, korman/properties/modifiers/sound.py, korman/ui/modifiers/physics.py, korman/ui/modifiers/sound.py
Fixes #165
Closes #212
Depends on H-uru/libhsplasma#206
[Sample Age](https://github.com/H-uru/korman/files/6412755/KormanRndSnd.zip)
TODO
=> Implement the Random Sound modifier.

korman/exporter/animation.py, korman/exporter/camera.py, korman/properties/prop_object.py
Put this together, through trial and error
There are probably better way to do this
Was able to export quaternion animation with it
=> Support for quaternion rotation animations

korman/exporter/convert.py, korman/exporter/etlight.py, korman/exporter/mesh.py, korman/operators/op_lightmap.py, korman/properties/modifiers/render.py, korman/ui/modifiers/render.py
It's better to trust the artist to know what they are doing if they provide a uv map for the lightmap modifier to use. Closes #265.
=> Don't touch my UV maps!

korman/exporter/convert.py, korman/exporter/mesh.py
Fixes issue reported on the [forum](https://forum.guildofwriters.org/viewtopic.php?p=75582#p75582) by denwaler. @Jrius does this look good to you? I know you've mentioned before that the previous Korman behavior was iffy.
=> Fix weird node warping.

cmake/Dependencies.cmake, korman/exporter/material.py, korman/exporter/mesh.py, korman/properties/modifiers/render.py
Requires corresponding HSPlasma fix (attached for 2.79b).
[2.79.zip](https://github.com/H-uru/korman/files/7050311/2.79.zip)
=> Fix RT lit material shading animations

korman/exporter/animation.py, korman/exporter/camera.py, korman/exporter/convert.py, korman/exporter/material.py, korman/nodes/node_messages.py, korman/properties/__init__.py, korman/properties/modifiers/anim.py, korman/properties/prop_anim.py, korman/properties/prop_camera.py, korman/properties/prop_texture.py, korman/ui/__init__.py, korman/ui/modifiers/anim.py, korman/ui/ui_anim.py, korman/ui/ui_camera.py, korman/ui/ui_texture.py
=> Multi animations

korman/exporter/material.py
Updates an older code definition to fix an error with SDL layer animations.
=> SDL Variable Fix

korman/exporter/material.py
Fixes a few items with runtime lighting and lightmapping
=> Small runtime fix

korman/ui/ui_menus.py
As suggested in #191, this moves the functionality for building menus into class methods for each menu.
=> Use class methods to build menus.

korman/exporter/material.py
=> Allow per-texture emit.

korman/properties/modifiers/gui.py, korman/ui/modifiers/gui.py
Adds a "Shareable" toggle to Linking Book Mod when Link Type is set to Private Link (MOUL only).
=> Add Share Function to Linking Book Mod

korman/nodes/node_python.py
Adds a needed animation picker for new named animations for the Python script texture node. Code borrowed from node_messages.py
=> Add named animation EnumProperty

korman/nodes/node_messages.py
Allows the user to choose the type of callback for a responder sound message node like the animation node.
=> Add Callback EnumProperty to sound message node.

korman/nodes/node_python.py
Fixes a small error preventing Python animation attributes from exporting.
=> Fix error when exporting Python animation attributes

korman/properties/modifiers/logic.py, korman/ui/modifiers/logic.py
Adds properties and UI for a modifier to set up a clickable telescope.
=> Telescope Modifier

korman/exporter/mesh.py, korman/properties/modifiers/base.py, korman/properties/modifiers/render.py
Adds the Late export for blend pass exporting meshes
=> Add Late Render Pass

korman/nodes/node_messages.py, korman/properties/modifiers/physics.py
=> Add the Change Subworld message node.

korman/nodes/node_avatar.py, korman/nodes/node_conditions.py, korman/nodes/node_deprecated.py, korman/nodes/node_logic.py, korman/nodes/node_messages.py, korman/nodes/node_responder.py, korman/nodes/node_softvolume.py
Relates to this issue: https://github.com/H-uru/korman/issues/398
I also have added type annotations :)
=> Removed the `OrderedDict`s
