korman/exporter/material.py, korman/operators/op_toolbox.py, korman/properties/__init__.py, korman/properties/prop_texture.py, korman/ui/ui_texture.py, korman/ui/ui_toolbox.py
- Add an opacity value for exported layer.
- Add a conversion button in the toolbar for old PyPRP Ages
which used the diffuse color factor as the opacity value.
=> Add Plasma layer options panel to Texture context.

korman/plasma_attributes.py
Some of Cyan's old scripts predate Python supporting Booleans, which leaves us with variables where we expected constant values. This change intercepts these cases and replaces them, avoiding an exception in Korman when it tries to shove one of these strings into a boolean attribute.
Also included is a new visitor for proper name constants, support for which was added in Python 3.4.  This will allow future scripts to use them and be recognized correctly.
=> Fix parsing of Python scripts which use variable Booleans.

korman/properties/modifiers/render.py, korman/ui/modifiers/render.py
This adds a unified opacity fade modifier.  The artist can choose between a distance-based fade, a simplified distance-based fade (primarily for use on GZ markers), or a line-of-sight-based fade.
This closes #12 and #13.
=> Add plDistOpacityMod and plFadeOpacityMod.

korman/exporter/material.py, korman/exporter/physics.py, korman/properties/modifiers/anim.py
Set mass=1 and kPinned for non-kickable physicals having a CoordinateInterface, so they can be animated.
Don't force clamping for texture stencils, so they can be tiled if necessary.
More infos : [https://forum.guildofwriters.org/viewtopic.php?f=2&t=6574&p=69469#p69469](url)
=> Animated physicals + no clamped stencils

korman/exporter/mesh.py
Really I guess this is implementing *non-smoothing*, since we previously treated all faces as if they had smoothing enabled.
It's technically a breaking change, but should make Plasma with runtime lighting match what you'd expect from the Blender 3D viewport.
It also matches how PlasmaMax treats meshes by default with no smoothing groups attached.
=> Implement face flat/smoothing shading

korman/exporter/animation.py
If you had only transform animations on a lamp, it would still attempt to unconditionally export colour/falloff animations.
This early exit was in the LightInfo conversion method, but missing from the OmniLight and SpotLight methods.
=> Fix exporting lamp animations

korman/exporter/animation.py, korman/exporter/rtlight.py
When `use_sphere` is enabled, the lamp cutoff is at exactly the distance value. Otherwise, the distance value is the point at which the lamp intensity is half its starting value.
This probably doesn't match Blender 1-to-1, but it's closer to Blender's lighting logic than the existing `use_sphere` calculations.
=> Fix backward lamp distance calculation

korman/exporter/animation.py
I ran into this problem when animating a texture. Normally when setting keyframes, all axes of a transformation are keyed. However if only a subset of all axes is actually manipulated in the animation (and the rest left constant), the keyframes for the other axes can be removed. One reason to do so is to make it clear what aspects are being animated. For example, a water texture that only moves along its X axis does not need keyframes for its Y and Z axes.
In the original code, the assumption was made that all keyframes had X, Y and Z components. Thus an error was raised on line 324, where elements of a dict are accessed that do not exist. By making use of the `pos_default` parameter, these missing values can be filled in by the static values of these properties.
=> fix animation exporter not being able to handle missing axes

korlib/texture.cpp, korman/__init__.py, korman/exporter/convert.py, korman/exporter/etlight.py, korman/exporter/logger.py, korman/exporter/material.py, korman/exporter/mesh.py, korman/exporter/rtlight.py, korman/korlib/__init__.py, korman/korlib/console.py, korman/korlib/texture.py, korman/nodes/node_conditions.py, korman/operators/op_export.py, korman/properties/modifiers/render.py, korman/properties/modifiers/sound.py
A common complaint that I have heard (and have myself) is that there is little indication of what Korman is doing in the background. Unfortunately, there is no "easy" way to show progress in the Blender UI currently. Korman makes the assumption that nothing will touch Blender's context while it is executing. Attempts to move the exporter into a background thread such that Blender's UI remains active have all resulted in spectacular failures.
In PyPRP, the raw export log was dumped to the console, and many liked to watch it travel by as an indicator of progress. As such, I have implemented a progress monitor that outputs to the console into the export logger. The console now opens during the export (unless disabled in the export operator) to show the export progress. The export operator …
=> Improved export progress logging

korman/exporter/material.py
Okay, so this is purely for the sake of technical correctness, because `kBlendDetail` is handled identically to `kBlendAlpha` for rendering purposes
=> Set kBlendDetail flag on detail blends

korman/exporter/material.py
Refraction Xform causes the camera movement to affect the resulting output differently, leading to an envmap that seems to run around the object in the opposite direction as you turn.
Reflection Xform keeps it much more steady, and also matches what PlasmaMax outputs by default (they have a checkbox to use Refract mode).
=> Use Reflection Xform for env maps

korman/nodes/node_python.py, korman/operators/op_nodes.py, korman/plasma_attributes.py
This adds the necessary code for the parsing and storage of PFM arguments in the PythonFileNode, for use by the AttributeNodes when appropriate.  
It allows us to do range feedback (Property min and max can't be modified at runtime, so we change the input to an error color) and utilize the strings specified to populate options for DropDownLists (and other list-type nodes to-be-implemented).
It also fixes a missing visitor in the initial parser script which incorrectly skipped negative numbers.
Closes #59.
=> Add support for PythonFileNode attributes arguments.

korman/nodes/node_core.py, korman/nodes/node_python.py
Simple value nodes take up far too much room in the node tree.  This little helper lets us define an attribute to check and display as the label when a node is collapsed.
=> Show value of simple nodes in their label when collapsed.

korman/__init__.py, korman/nodes/node_python.py, korman/operators/__init__.py, korman/operators/op_mesh.py, korman/properties/modifiers/avatar.py, korman/ui/__init__.py, korman/ui/modifiers/avatar.py, korman/ui/ui_menus.py
Adds the plAvLadder modifier, and also a new Plasma submenu to the `shift-A` Add menu.  This menu contains our first premade mesh guide, the Ladder.  
The ladder mesh operator automatically generates guides which show the artist where the climb animation will line up, and the entry regions (if desired) have their plAvLadderMod enabled and pre-configured.
Closes #44.
=> Add Ladders.

korman/exporter/mesh.py
We're only a BlendSpan if the *first* layer of a material has a blend. Other layers are permitted to have blend modes, because those don't affect the blending of the span itself against other spans.
This matches the behaviour of PlasmaMax:
https://github.com/H-uru/Plasma/blob/42c4acbc9d2ddf7e0d4486ba3edfdd6c40e2f84b/Sources/Tools/MaxConvert/plMeshConverter.cpp#L1205-L1210
=> Fix Span/BlendSpan discriminator

korman/exporter/mesh.py, korman/properties/modifiers/render.py
Not 100% sure about this, but it was needed in my case to get a lamp flare to render without haloing (in combination with a passIndex to force it into a new BlendSpan).
This is where more rendering modifiers might make sense...
=> Sort spans for opacity modifiers

korman/exporter/material.py
If the material wants to emit, we'll emit the diffuse colour instead of the world's ambient colour (which pretty much always needs to be black or everything will look wonky)
Also, if we're shadeless, emit white (but do it at runtime via the kShadeWhite flag)
=> Handle shadeless & emit material flags

korman/exporter/material.py
This causes the layer to just be entirely transparent.
=> Don't set multiple exclusive blend flags

korman/properties/modifiers/avatar.py
Apparently pre-MOUL ladders can't have massless regions as detectors anywhere but at the origin, so this adds the required values to make sure the export puts each one in the correct location in PotS.
Fixes #93.
=> Fix ladder detector regions for PotS exports.

korman/nodes/node_core.py, korman/nodes/node_deprecated.py, korman/nodes/node_responder.py, korman/properties/modifiers/region.py
This changeset enables Responder nodes to track Responder State nodes individually and report their ID to the user for easier integration into Python scripts. This seems like a good companion for #95 in Korman 0.07
Fixes #100
=> Responder State IDs

korman/exporter/convert.py, korman/exporter/etlight.py, korman/exporter/mesh.py, korman/operators/op_export.py, korman/properties/__init__.py, korman/properties/modifiers/render.py, korman/properties/prop_scene.py, korman/ui/__init__.py, korman/ui/modifiers/render.py, korman/ui/ui_render_layer.py, korman/ui/ui_world.py
This fixes #118 by adding named lightmap passes. It is no longer possible to specify render layers on a per-object basis. Instead, a pass must be set up. Old modifiers are silently upgraded and consolidated into passes when the blend file is loaded. The old default behavior is equivalent to specifying no pass on the new modifier.
Additionally, I have generalized the lightmap modifier by allowing the artist to change to vertex shading mode and specify the layers to bake with. The "bake static lighting" checkbox has been changed to a dropdown in which light baking can be turned off completely, all lightmaps can be forced to vertex colors, all arist-specified vertex colors can be forced to lightmaps, or the blissful default. I did not add the option to force auto-vertex colors to lightmaps, …
=> Add named lightmap passes

korlib/korlib.h, korlib/module.cpp, korlib/texture.cpp, korlib/texture.h, korman/exporter/convert.py, korman/exporter/image.py, korman/exporter/material.py, korman/helpers.py, korman/korlib/texture.py, korman/operators/__init__.py, korman/operators/op_export.py, korman/operators/op_image.py, korman/operators/op_toolbox.py, korman/ui/ui_texture.py, korman/ui/ui_toolbox.py, korman/ui/ui_world.py
This changeset allows the artist to control how Korman exports dynamic environment maps at export time due to their ability to cause ages to slow down. One specific concern was that Dynamic Camera Maps were being silently downgraded to Dynamic Environment Maps (from 1 face to 6 faces) when exporting to Path of the Shell.
Also included is the ability to export cube maps as `plCubicEnvironmap` objects. Korman will take a Blender cube map (six faces in one image) and split it into six different face images. This nesecitated a rather large rewrite of the image data handling code. We now do all of the mipmapping on the CPU in Korman code as a result. This is both a good and bad thing in that 1) we are no longer reliant on a deprecated OpenGL feature, 2) the pure Python image scaling code is …
=> Environment Map Improvements

korman/exporter/convert.py, korman/nodes/node_avatar.py, korman/nodes/node_conditions.py, korman/nodes/node_core.py, korman/nodes/node_logic.py, korman/nodes/node_messages.py, korman/nodes/node_python.py, korman/nodes/node_responder.py, korman/nodes/node_softvolume.py, korman/properties/modifiers/logic.py, korman/properties/modifiers/region.py, korman/ui/modifiers/logic.py
Previously, reusing node trees required careful thought and specification of specific nodes in the advanced logic modifier. This tedious requirement has been removed in favor of ensuring that the nodes themselves take into account whether or not they should generate and attach plasma objects.
=> Make node trees reusable.

korman/nodes/node_core.py
This fixes two bugs with empty node socket spawning:
- The first time an empty is spawned, the link is moved to the last socket.
- Unlinking a socket in the middle of the group would cause that socket to be the one that's empty. This isn't bad per-se, but with Responders being ID-based, it could result in some confusion.
Beware: due to code movage, the diff looks strange.
=> Fix interesting empty node socket spawning bugs.

korman/addon_prefs.py, korman/exporter/__init__.py, korman/exporter/explosions.py, korman/exporter/logger.py, korman/operators/op_export.py, korman/plasma_launcher.py, korman/ui/ui_world.py
This is implemented by adding a separate script to act as a client watchdog. In CWE/MOUL, the watchdog simply starts the client with the requisite options. In PotS, we utlize PyHSPlasma's vault bindings to set the OfflineKI AutoLink chronicle. The watchdog resets the chronicle when the game closes if the user did not change its value while in game.
Closes #159.
=> Add the ability to launch URU from Korman.

korman/exporter/explosions.py, korman/exporter/material.py, korman/ui/ui_texture.py
This adds support for the BlendTexture type to the material exporter. This has been done in preparation for #155, which will need alpha blend layers to be generated for certain footprint materials. The math was, in some cases, lifted from PyPRP.
=> Add Blend Texture Exporter

korman/exporter/utils.py, korman/operators/op_mesh.py, korman/ui/ui_menus.py
This adds a new item to the `Add...Plasma...` menu which creates a set of pre-configured Linking Book objects.  It creates a guide the artist can line up with the linking panel on a linking book, along with a seek point and clickable region parented to the panel guide, as well as an enabled Linking Book modifier.  The seek point is placed at a pre-computed position so that it lines up with the linking panel guide properly for both the standing and kneeling Link Animations.
=> Add Linking Book guide.

korman/nodes/node_avatar.py
This adds descriptions to the node's fields which were accidentally left out of #124.
=> Add missing descriptions for PlasmaAnimStageSettingsNode properties.

korman/operators/op_mesh.py, korman/ui/ui_menus.py
This adds a new item to the `Add...Plasma...` menu which provides a pre-configured lamp flare.  
It creates a set of objects for an optimal, general-purpose glow around most lamps:
- An empty with a Swivel modifier at the chosen location (usually the lamp).
- A plane parented to the empty for the flare texture, with an Opacity Fade modifier which uses the plane's center for Line-of-Sight.
=> Add premade Lamp Flare.

korman/operators/op_mesh.py
This partial code was unintentionally included in #182, and causes the Lamp Flare feature to be non-functional.
=> Remove spurious code in lamp flare operator. 

korman/exporter/convert.py, korman/exporter/utils.py
Added export / conversion function for turning font objects into mesh objects that can be exported to Plasma.
Since I'm using so many font objects, I found myself wanting Korman to just automatically export them, instead of manually converting and managing a bunch of mesh copies. Thought I would take a crack at it, and managed to get it working.
Uses operators (discouraged practice, I know, but I couldn't figure out how to do it using low level functions after spending more time than I wanted looking through old Blender Python API documentation)
Deselects everything, selects the current blender object, converts it, then hands it over to the mesh export function, keeps the original and cleans up by deleting the converted mesh after export.
=> Font Export

korman/exporter/camera.py
Keeps Korman from exporting a rail camera with only one keyframe (or duplicate location keyframes), the former of which causes the client to crash.
=> Fix Rail Camera keyframe issue

korman/operators/op_toolbox.py, korman/ui/ui_toolbox.py
Adds toolbar options to toggle meshes double sided, one to Disable All (handy for incoming PyPRP Ages) and Enable/Disable Selection.
I thought about an Enable All button, but didn't know if there would ever be a reason to use a function like that.
=> Add Double Sided Toolbox Operators

korman/ui/ui_menus.py
This adds a Help menu to the appropriate place in Blender.  It provides links to common documents of use to Age builders.
=> Add Help menu for Korman.

korman/operators/op_toolbox.py, korman/ui/ui_toolbox.py
Adds buttons to the toolbar to enable and disable export/packaging of sounds (WIP).
Some issues at the moment:
- Enable/Disable selected is not toggling properly, both in function and button text (currently disabled for now).
- Enable/Disable All buttons are working, but the effect (ie the "Export" checkbox) does not display immediately on-screen until the cursor hovers over the sound mod.
=> Add Sound Export Operator Buttons

korman/exporter/material.py, korman/exporter/mesh.py, korman/idprops.py, korman/properties/modifiers/__init__.py, korman/properties/modifiers/base.py, korman/properties/modifiers/render.py, korman/ui/modifiers/render.py
This is designed to fix some issues around non-animated runtime lights not affecting geometry and challenges around alpha transparency and x-ray effects. We do so by properly using the `kLiteVtxNonPreshaded` equation for alpha and runtime lit geometry. Further, preshade and runtime colors are now properly set for runtime lit and emissive layers.
Adds the Render > Blending modifier to ensure dependent objects get sorted into later passes.
=> DSpan Export Improvements

korman/exporter/animation.py
Keyframes need negative values in order for sound volume animations to work properly, and this change, per Hoikas, will fix this.
=> Fix volume animation conversion

korman/exporter/manager.py, korman/exporter/material.py, korman/nodes/node_python.py
This is an attempt to address some more issues with runtime lighting, Particularly, we now force any light attached to a PFM to be `kLPMovable` - because the only reason you would attach a light to a PFM is to either warp it or turn it on/off. Further, we now export the layer runtime color as the material diffuse unless preshading is explicitly off. The behavior change is subtle, but we only want to set runtime to black in the case of purely dynamic lighting. Otherwise, we end up restricting receiving runtime lighting to only objects that are `kLiteVtxNonPreshaded` because `kLiteMaterial` multiples the runtime color by the lamp color.
=> More DSpan Lighting Fixes

korman/exporter/manager.py, korman/properties/prop_world.py, korman/ui/ui_world.py
This was something minor that came up awhile back. For some reason, SetDefExp2 type fog doesn't seem to work upon export in either MOUL or PotS/CC, but regular SetDefExp does. This is just a proposed minor change to use the regular SetDefExp option if fixing the other is too big a task.
Yeah, could probably have left everything except `Graphics.Renderer.Fog.SetDefExp` alone, but I figured we'd want things uniform across the board. 😉
=> Fix Exponential Fog

korman/exporter/manager.py
This rounds the funny file values so that long strings of float imprecision errors don't wind up in the exported funny files, making them even funnier than they already are.
=> Round funny values to hide float precision details.

korman/exporter/animation.py, korman/properties/modifiers/anim.py, korman/ui/modifiers/anim.py
Adds SDL Global animation to Korman per #204 (work in progress).
What it does so far:
* Adds SDL field to Animation modifier. ~~Note that it's only available if "Loop Anim" is selected (is this OK?).~~
* Creates ~~what appears to be~~ an ~~valid~~ Age Global Animation (plAgeGlobalAnim) entry into the PRP files ~~aside from one flaw (see below)~~.
A few things to fix:
* ~~SDL parameter from modifier isn't being written to AgeGlobalAnim's "GlobalVarName" entry.~~ Fixed thanks to dpogue.
* ~~Global Animation being created for non-object animations (layer animations), causing glitching.~~
* ~~Some extra ATC parameters (says it needs fixing?)~~
* "Writing Age data..." part of export is hanging for several seconds, most likely due to mah hacks. 😉 
* ~~Global Animation also creates a near-empty …
=> Add plAgeGlobalAnim support

korman/exporter/convert.py, korman/exporter/mesh.py, korman/exporter/physics.py
Current fixes:
- Fixed an issue in which font (read: text) objects would appear at the origin when parented to another object. This happened because font objects were being silently exported to a different SceneObject than anticipated.
- Fixed an issue in PotS where any physical parented to another object fell through the floor on link in due to the physical not being pinned. Any physical in local space in PotS needs to be pinned, otherwise it starts moving under the influence of gravity.
- Fixed an issue in MOUL where any physicals in a subworld were exported in the wrong coordinate system. They were exported in local-to-world space, but MOUL expects them in local-to-subworld space. This caused the physicals to be offset inappropriately in the world, generally causing the player to fall …
=> Fix many issues with parented physicals.

korman/exporter/material.py, korman/properties/prop_texture.py, korman/ui/ui_texture.py
Adds a Bool property in the Plasma Environment Map panel to toggle avatar rending (fixes some waveset rendering problems)
=> Toggle EnvMap Avatar Render

korman/exporter/camera.py, korman/properties/prop_camera.py, korman/ui/ui_camera.py
Adds support for first person camera objects such as the baron's office desk. Disappears the avatar as well.
=> Add First Person Camera Object

korman/nodes/node_conditions.py
Just like clickable nodes, region sensor nodes now assume their receivers to be attached to the parent_so (the object with the Advanced Logic modifier) instead of attached to the region itself.
Previously, a region sensor would instead create its own new empty receiver (say, a Responder with zero states) and notify it instead of the real responder, rendering it useless.
=> Region sensor: assume receiver on parent_so instead of own sceneobject

korman/idprops.py, korman/properties/modifiers/anim.py
Pretty much what it says. The GroupMaster modifier expects to find animation data on the `object` itself and doesn't check the `object.data`, thus preventing you from adding an animated lamp to its list. This fixes that.
=> Allow GroupMaster (MsgForwarder) to animate object data (such as lamps)

korman/exporter/animation.py, korman/exporter/material.py
Blender's texture slot scaling is done from the center (0.5, 0.5) of the UV mapping viewport, with Y axis up. Plasma's scaling is done from origin (0, 0), with Y axis down. Ah, D3D and OpenGL...
=> Convert layer offsets to Plasma's space

korman/exporter/material.py, korman/exporter/mesh.py
I'm not really sure what value an emissive lightmap has, but apparently people use them. So, it's better to give not-quite-so-emissive results instead of breaking the entire Age's rendering.
=> Fix emissive lightmaps broken by a203e10.

korman/exporter/rtlight.py
Enable shadow-only lamps.
This is what I did to enable shadow-only lamps. It might seem counter-intuitive. I know that other lighting work is underway so this could already be moot.
=> Enable Shadow-only Lamps

korman/exporter/convert.py, korman/exporter/etlight.py, korman/operators/op_lightmap.py, korman/properties/modifiers/render.py, korman/ui/modifiers/render.py, korman/ui/ui_toolbox.py
This changeset allows reusing the same baked lighting from one export to another. This is an opt-in feature for when your Age becomes lighting heavy and the performance penalty becomes expensive when trying to iterate on other aspects of the Age.
New operators have been added. In the toolbox, you can "Bake All" or "Bake Selected" lighting at any time. In the lightmap modifier, you can "Bake for Export". These buttons bake vertex colors to the "Col" layer or set the new "Image" field on the lightmap modifier, as appropriate. On export, if a "Col" or image texture is found, it is used instead of lighting being rebaked. This means that if the lighting changes on those objects YOU have to rebake them using these same features. To return to the previous functionality of rebake every export, …
=> Persistent Baked Lighting

korman/exporter/manager.py, korman/properties/prop_world.py
Reintroduces the Exp2 Fog option for completion and ZLZ importation reasons and also updates the "none" fog function description.
=> Add Back Exp2 Fog

korman/exporter/etlight.py
Based on Hoikas' PR, so marking this as draft for now.
Improved algorithm to remove vcol baking artifacts while preserving sharp edges. Most efficient on meshes mixing smooth and sharp edges. Some objects with lots of sharp edges might still display the dark color bugs - in my experience this rarely happens, more testing will probably be required due to the random nature of the bug. On an Age the size of Tsoidahl Prad, this process takes about 2.3 seconds.
Hats off if you understand the smoothing algorithm on the first read - the whole process of comparing vertices and loops is kinda tricky. Note that I'm also ramming the object through BMesh, so I had to manually track active vertex color layers instead of relying on GoodNeighbor.
=> Vcol artifacts removal

korman/exporter/rtlight.py
I'm probably late to the party, but I have found that PotS can't handle more than 8 RT lamps on one material. This might vary by target engine, though, so no failure pronouncement is made.
=> Warn if more than 8 RT lamps are on a material.

korman/exporter/material.py, korman/properties/modifiers/render.py, korman/ui/modifiers/render.py
If we've unleashed Satan on a material, he will perform his dark magick on the material colors. Therefore, we need to prefix the satanic materials with something other than "RTLit_" lest the plain old runtime lit materials be subjugated by the prince of darkness.
Fixes #240
=> Clearly deliniate the circles of hell.

korman/exporter/rtlight.py, korman/nodes/node_python.py
It looks like simply attaching a lamp to a group already has fairly major implications for how it's exported. If you're adding a lamp into a group, then you are basically saying, "I only want to affect these specific objects.", so marking them as movable (meaning, "apply me to all objects") doesn't really make sense in that context.
Fixes #264
CC @DoobesURU
=> Don't mark lights in a group as `kLPMovable`.

korman/exporter/mesh.py, korman/exporter/physics.py, korman/exporter/utils.py
Fixes regression introduced in #274 and applies the same fix to other vulnerable places in the physics exporter. The problem is that while negative scaling SHOULD invert the mesh normals, Blender's renderer does not actually invert the normals if an object has negative scaling. The only way to see this in Blender is to apply scaling with Ctrl+A S. The result is an unpleasant surprise once the Age is exported. So, we will now just export the "wrong" normals so the results aren't surprising.
=> Fix regression in negative object scaling.

korman/exporter/animation.py, korman/exporter/camera.py, korman/exporter/convert.py, korman/exporter/material.py, korman/exporter/mesh.py, korman/exporter/physics.py, korman/exporter/utils.py, korman/properties/modifiers/avatar.py, korman/properties/modifiers/gui.py, korman/properties/modifiers/water.py, korman/properties/prop_camera.py
Alright, this should mostly fix #284.
What this does:
- Replace all `object.location` with `object.matrix_world_transform`, since `object.location` is not reliable as world transform.
- Replace all `object.matrix_basis` with `object.matrix_local` when we want to access local transform.
- Fix a few smallish issues I noticed while I'm at it (such as `bo.name` in `generate_flat_proxy`).
- Apply `object.matrix_parent_inverse` to animations to _attempt_ to make them truly local.
Emphasis on "attempt", because mathematically, animations in non-local space cannot always be represented via local-space T/R/S anims. Also, wide euler rotations can cause issues due to being converted to quats and back to eulers; and mixing complex scaling/rotation in the parent & child can have some odd results. …
=> Matrix anim fix

korman/properties/modifiers/render.py
Quick fix for a small oversight. The Blending modifier's `self.name` property is always an empty string. We want to use the Blender object name instead.
=> Fix error in render dependency check

korman/exporter/mesh.py
Fixes a small issue with Korman's vertex de-duplication code.
Korman compares vertex color/uvws in order to determine if a vertex has already been exported. However, uvws are stored in `bpy_prop_array`s, which are compared by reference and not by value.
This results in Korman exporting exactly 3 vertices per triangles, which also means lower vertex count limit, slightly worse ingame performances, etc.
Casting the `bpy_prop_array`s to tuples fixes that. The difference can be observed by reimporting Ages using ZLZ with the "Normals: None" option.
=> Fix vertex duplication

korman/properties/modifiers/sound.py
Makes Korman aware of relative filepaths such as `//sounds/my_sound.ogg` for sounds.
=> Sounds: allow paths relative to the Blender file.

korman/properties/modifiers/water.py
Since I'm currently doing some PRs, might as well submit this...
Changes the default buoyancy/velocity for swimregions to match Ahnonay's. The avatar doesn't dive as deep, but resurfaces much faster. Feels more natural IMO.
Fixes #291.
=> Ahnonay default buoyancy for swimregions

korman/exporter/etlight.py
Vertex color cleaning (#270) can fail on some polygons, which results in random vertices being fully white.
This is caused by a Blender bug, which prevent baking loops made of three aligned vertices when using polygons instead of regular tris/quads. This is rare but can happen with some workflows. (The bug itself is probably because of something like triangulation problems within Blender).
We detect such cases with `loop.is_convex`. Convex loops are those for which the angle between the two connected edges is superior or equal to 180°.
(Ideally we should check whether the angle is exactly 180°, but that can be a bit tricky due to floating point precision. `is_convex` still yields good enough results AFAICT, and takes care of the main issue.)
=> Fix vcol cleaning bug with polygons

korman/properties/modifiers/water.py
Changes amplitude property from int percentage to a three digit float for more precision, which fixes "wobbly" geostate waves.
=> Fix Waveset Amplitude

korman/exporter/material.py
Dynamic envmaps have a "FogStart" attribute. By default it should be set to a negative number to let the engine use the current fog settings, [as seen here](https://github.com/H-uru/Plasma/blob/master/Sources/Plasma/FeatureLib/pfDXPipeline/plDXPipeline.cpp#L4082).
Setting it to zero or a positive number will fiddle with fog settings in a way we probably don't want. I don't know the specifics, but in my case this makes the fog disappear from reflective objects (such as large bodies of water).
=> Dynamic envmap: let the engine use default fog settings.

korman/operators/op_mesh.py
Removes opacity fader from the flare mod, which has been causing problems for end users.
I'm open to possibly adjusting the settings to make things work properly initially if that's preferred. Currently, the settings cause the flares to "blink" out at odd angles per both myself and Tweek. It could also be argued that it could/should be left up to the end user whether to add it.
=> Remove Opacity Fader from Plasma flare function

korman/nodes/node_messages.py, korman/properties/modifiers/sound.py, korman/ui/modifiers/sound.py
Adds the "Local Only/kIsLocalOnly" property to sound emitter modifiers. Dependent on the kPropIsLocalOnly attribute, which still needs to be added to libHSPlasma (unless I'm using the wrong definition?).
This will allow better sound control per client/avatar, which Ages like Tiam and Descent will need.
=> Add Local Only to Sound Emitter Modifier

korman/exporter/physics.py, korman/properties/modifiers/physics.py, korman/ui/modifiers/physics.py
Exports a collider that should hopefully block only dynamic objects (kickables). Also, some formatting adjustments to the properties script to match others (this can be undone if wanted)
=> Add kDynamicBlocker collider toggle.

korman/exporter/physics.py, korman/nodes/node_conditions.py, korman/ui/modifiers/region.py
This addresses some common gotchas with exported colliders:
- Flat convex hulls (planes) are now forced to triangle meshes.
- Triangle mesh regions will cause the export to error on MOUL and Myst V mode because the physics engines in those games either do not support this combination or only partially support it.
- Triangle mesh regions now alert in the UI, where appropriate.
=> A batch of collider usability improvements.

korman/properties/modifiers/avatar.py, korman/ui/modifiers/avatar.py
Adds new scripting to Sitting Modifier to use xSitCam.py if a camera is selected.
Note that, as of the first commit, the camera object does not attach to the proper node in the Python file script node and I'm not entirely sure why. **EDIT: This has since been fixed (see comment below).**
=> Add xSitCam.py functionality to Sitting Modifier

korman/properties/modifiers/water.py
If a wind object is *not* animated but rather moved via logic nodes (eg a Python script), then the previous logic wouldn't allow for the in-game wind direction to change. It's important to check if the wind object has a coordinate interface (can it move?) instead of if it's animated (did the artist move it?).
=> Fix potential wind object gotcha.

.github/workflows/ci_build.yml
This revision of B4K re-enabled the Cycles Renderer, which was disabled due to a bug in MSVC when B4K was previously rebuilt for a critical bug fix.
=> Bump to B4K 2022-11-13.

cmake/Dependencies.cmake, korman/plasma_launcher.py
Recap: There is a bug in Windows where file IO with the C apis can race if the operations occur in separate processes. This means that sometimes the TPotS auto-linking feature would link you to the wrong Age due to reading an old/cached copy of the vault file.
This was fixed in H-uru/libhsplasma#242 originally, but Win32 APIs seem to have terrible performance without user mode buffering, which negatively impacted PRP loading in other tools, such as PRP Shop. Therefore, the fix was reverted in H-uru/libhsplasma#246. This fixes the race condition closer to the point of impact using the Win32 stream introduced by H-uru/libhsplasma#264.
This is a draft until H-uru/libhsplasma#264 is accepted.
=> Re-fix the TPotS launching race condition.

korman/exporter/outfile.py
These attributes are strings, not paths. It is safe to format with a path -- paths are implicitly convertible to strings by formatters. We use a `PurePath` because we only care about getting the string name and not actually performing any path manipulation.
CC @ Traveler263 please try this fix.
Fixes #361
=> Fix `TypeError` in outfile warning message.

korman/nodes/node_messages.py, korman/nodes/node_responder.py
Fixes:
```
Traceback (most recent call last):
File "D:\Korman 0.14\2.79\scripts\addons\korman\operators\op_export.py", line 228, in execute
e.run()
File "D:\Korman 0.14\2.79\scripts\addons\korman\exporter\convert.py", line 118, in run
self._export_referenced_node_trees()
File "D:\Korman 0.14\2.79\scripts\addons\korman\exporter\convert.py", line 336, in _export_referenced_node_trees
tree.export(self, bo, so)
File "D:\Korman 0.14\2.79\scripts\addons\korman\nodes\node_core.py", line 503, in export
node.export(exporter, bo, so)
File "D:\Korman 0.14\2.79\scripts\addons\korman\nodes\node_responder.py", line 136, in export
stateMgr.convert_states(exporter, so)
File "D:\Korman 0.14\2.79\scripts\addons\korman\nodes\node_responder.py", line 113, in convert_states
node.convert_state(exporter, so, …
```
=> Don't try to sort with `None`.

korman/nodes/node_conditions.py, korman/nodes/node_core.py
This allows Region Sensor nodes to export `plObjectInVolumeAndFacingDetector`, which only triggers the region sensor when an avatar is in the region, facing a certain direction (within a tolerance amount), and (optionally) moving forward.
BREAKING CHANGE: The Facing Target node can now only link to a single condition node.
A companion pull request is available for Plasma to ensure that swimming forward satisfies the moving forward condition. See H-uru/Plasma#1362.
A [test Age blend file](https://github.com/H-uru/korman/files/11008971/ObjectInVolumeAndFacing.zip) is available.
Closes #360.
=> Allow facing detectors for region sensors.

korman/nodes/node_core.py, korman/nodes/node_responder.py
When a responder node is linked to a Python file node's ptAttribNamedResponder socket, it will now export with the same name as the node itself. In that way, the responder can be addressed in the attribute's value mapping in the Python script itself.
Closes #346.
CC @DoobesURU for verification.
=> Improve handling of `ptAttribNamedResponder`.

korman/exporter/utils.py, korman/operators/op_mesh.py
This fixes review comments left on #367 that were caused by missing pretends-to-be-a semantics. `BMeshObject` is intended to provide pass-through access to `bpy.types.Object`'s attributes.
Supercedes and closes #369.
=> Fix incorrect pretends-to-be-a semantics from #367.

korman/exporter/animation.py, korman/helpers.py, korman/nodes/node_messages.py, korman/properties/modifiers/anim.py, korman/properties/modifiers/sound.py
In an attempt to address [#359](https://github.com/H-uru/Plasma/issues/1353), I separated 3D stereo sounds into separate emitter scene objects and allow the engine to position them around the listener such that the left channel is actually on the left of the listener (and the same for the right channel). Unfortunately, this did not fix the bug in question. However, the code that interfaces with sounds from the outside is now much simpler, and the improved behavior is a win, IMO, so let's keep this.
Fringe benefit: unused sounds no longer export their sound volume animations.
=> Improve 3D stereo sound emitters.

korman/properties/modifiers/render.py
Doing this greatly improves the result of the text rendered to the dynamic text map when alpha blending is in use.
Before:
After:
Requires H-uru/Plasma#1398
=> Pass the `blockRGB` argument to xDynTextLoc in the Localized Text Modifier.

korman/exporter/material.py
* Adds a sanity check that raises an error if a CubeMap doesn't have an image set to it.
=> Fix CubeMap "No image" Bug

korman/exporter/utils.py, korman/properties/modifiers/gui.py, korman/properties/modifiers/logic.py
the `pre_export_optional_cube_region` function is a decent idea, but it predates the ability to do things like `foo = yield bar()` in `pre_export()` generator methods. So, we remove it in favor of yielding and assigning in one line. This should clean up some noisy warnings from Blender after the export is over.
=> Pay down some technical debt wrt cube regions.

korman/exporter/mesh.py
Weird feature request by artists. Korman's lighting equation selection looks like it should work fine with this, though. The key is to be sure that we don't pick up a stale autocolor layer.
Fixes #403
Supersedes and closes #402
CC @DoobesURU
=> Allow vertex colors to modulate lightmaps.

korman/exporter/utils.py, korman/properties/modifiers/base.py, korman/properties/modifiers/logic.py, korman/ui/modifiers/logic.py
This simplies the creation of "entry cameras" as seen in Doobes' Ages Veelay and Chiso. In Doobes' Ages, the entry cameras are pushed by entering into a region around the spawn point. When exiting the region, the camera is popped off and the region is disabled. Unfortunately, since this is a general purpose modifier, we cannot simply use that approach. That approach assumes there is a single spawn point for the entire Age. If you were to enter a second spawn point, then walk intgo the other spawn point's entry camera region, it would be spuriously triggered. Therefore, I have written a new `xEntryCam.py` script for CWE to ensure that all entry cameras are disabled when the local player finishes linking in.
See H-uru/Plasma#1556
=> Entry Cameras for the Spawn Point Modifier

korman/exporter/convert.py, korman/exporter/gui.py, korman/properties/modifiers/anim.py, korman/properties/modifiers/avatar.py, korman/properties/modifiers/game_gui.py, korman/properties/modifiers/gui.py, korman/properties/modifiers/logic.py, korman/properties/modifiers/render.py, korman/properties/modifiers/sound.py
Fixes #405. Side effect: fixes potential error where generated objects crash when pre-exporting.
CC @DoobesURU
=> Debounce duplicate note popups

korman/exporter/convert.py
> SyntaxWarning: assertion is always true, perhaps remove parentheses?
`assert` is a keyword, not a function, and using it with parentheses ends up being interpreted as a tuple argument (truthy) rather than a boolean assertion and a message
=> Fix syntax warning about assert

korman/enum_props.py, korman/idprops.py, korman/nodes/node_conditions.py, korman/nodes/node_logic.py, korman/nodes/node_messages.py, korman/nodes/node_python.py, korman/properties/modifiers/base.py, korman/properties/modifiers/game_gui.py, korman/properties/modifiers/logic.py, korman/properties/modifiers/physics.py, korman/properties/modifiers/region.py
This is a set of changes to de-duplicate code and storage of bounds and animation related properties. All bounds properties are now proxies to the collision modifier's bounds property with an automated upgrade path. All of the manual getters and setters in code that was already doing this have been removed and replaced with a helper to register bounds properties. Animation properties, especially material/texture animations, have been greatly simplified by removing verbose boilerplate around property registration.
=> Bounds and Animation Property Deduplication

korman/exporter/convert.py, korman/operators/op_ui.py, korman/plasma_api.py, korman/properties/modifiers/avatar.py, korman/properties/modifiers/base.py, korman/properties/modifiers/gui.py, korman/properties/modifiers/logic.py, korman/properties/modifiers/render.py, korman/ui/modifiers/logic.py
This centralizes the location of all PFM attribute stubs for easier maintenance and adds a modifier exposing xAgeSDLBoolShowHide and xAgeSDLIntShowHide. It should hopefully make life a little easier for creating global SDL controlled visibility type stuff.
=> Reorganize PFM Stub Storage and Add the SDL Show/Hide Modifier.

korman/exporter/manager.py, korman/nodes/node_python.py, korman/properties/modifiers/logic.py
* Fixes an error when a PythonFileMod tries to set itself as the proc for a GUIDialog (which happens when a dialog is passed in as a Python attribute)
* Fixes a case where GUIDialogs would get added as pool objects to the scene node, but also (incorrectly) get attached as modifiers to a SceneObject. This can cause Uru to crash because things load in the wrong order (which is its own problem that I'm not spending more time debugging tonight)
* Allow creating node trees in GUI pages. Sometimes you want a PythonFileMod in a GUI page, or sometimes you want a ResponderModifier in a GUI page.
* Fix a case where all ATC anims were being listed as pool objects which is not necessary except in the case of avatar animations (and those should in future probably be special cased like GUI pages are)
=> GUIDialog Python Proc fixes

korman/properties/modifiers/render.py
Certain animated objects, such as the flames for the Menorah in the city and the New Messengers Pub, need an empty that can swivel for both functions to work properly. If an animated object has both scale animation and swivel, it doesn't animate, for example. I noticed this while converting the city.
This PR will allow EMPTY objects to have swivel/FaceMod. See city/Ae'gura files and menorah dummy objects for examples of this.
=> Allow FaceMod/Swivel on Empty Objects

korman/ui/modifiers/render.py
Small addition to the Localized/DynText modifier to add a color picker for the font color in the font options. Utilizes the existing `font_color` def in properties.
=> Add Color Picker to DynText Modifier

korman/nodes/node_messages.py
Anim message node didn't pick up objects and spammed the console with errors. This fixes that.
(It does still allow selecting objects without a Korman animation modifier though, I don't know if it's intentional.)
=> Fix anim message not picking up objects

korman/properties/modifiers/water.py, korman/ui/modifiers/water.py
Fixes waveset wind direction export when a wind object is specified. Looks like it got lost in the last refactor...
=> Fix waveset export

korman/exporter/mesh.py
As it is now, Korman does not correctly export vertex normals as they appear in Blender.
Blender computes actual mesh normals (=what is used by the viewport for shading) according to (non exhaustive list):
- shared vertices between polygons
- polygon smoothness (`use_smooth`)
- edge sharpness (`use_edge_sharp`)
- mesh auto smooth+angle (mesh `use_auto_smooth` & `auto_smooth_angle`). Very useful for modelling machines with both smooth and sharp angles !
- potential custom split normals data (not sure how it works to be honest)
On export, Korman currently tries to reuse common vertices between polygons (which is good), but is a bit too eager and reuses vertices which are part of polygons with different normals. It also doesn't use the right property to get the actual normal that respects …
=> Correctly export vertex normals

korman/exporter/camera.py, korman/exporter/material.py
Fixes #423.
All `plCameraModifier` objects *must* have a brain or the client will crash dereferencing a null pointer. This commit audits all `plCameraModifier` creations and ensures that we are using a camera that will have a brain. There are probably better ways to do this, but I am le tired.
CC @DoobesURU
=> Add mitigations for #423.

korman/nodes/node_python.py
Fixes #424.
This is kind of a weird feature. You're now able to link a Python File node's (new) "Satisfies" socket to the `ptAttribActivator` socket on another Python File node. The Python File node that is the satisfier does not actually activate anything, though. It's really a way for the satisfied Python File node to communicate back to the satisfier.
CC @DoobesURU
=> Allow Python File nodes to activate each other.

korman/exporter/locman.py, korman/idprops.py, korman/operators/op_toolbox.py, korman/properties/modifiers/__init__.py, korman/properties/modifiers/game_gui.py, korman/properties/modifiers/gui.py, korman/properties/modifiers/render.py, korman/ui/modifiers/game_gui.py
Adds enough GUI controls to really do some damage.
Add:
- GUI Clickmap (`pfGUIClickMapCtrl`)
- GUI Checkbox (`pfGUICheckBoxCtrl`)
- GUI Draggable (`pfGUIDragBarCtrl`, `pfGUIDraggableMod`)
- GUI Color Scheme (`pfGUIColorScheme` - not actually a GUI control)
- GUI Text Box (`pfGUITextBoxMod`)
- GUI Radio Group (`pfGUIRadioGroupCtrl`)
- GUI DynamicDisplay (`pfGUIDynDisplayCtrl`)
- GUI Progress Control (`pfGUIProgressCtrl`)
- GUI Value Control (`pfGUIValueCtrl` - ABC)
- GUI Input Box (`pfGUIEditBoxMod`, `pfGUIMultiLineEditCtrl`)
Game GUI support is still ***ex***perimental, meaning all of these controls are subject to change without warning or concern for backwards compatibility.
After these are merged, we will only lack:
- `pfGUIKnobCtrl`
- `pfGUIListBoxMod`
- `pfGUIPopUpMenu`
- …
=> Implement Many, Many Game GUI Controls
